// Textes de l'interface, en français, regroupés par écran. Un texte à
// paramètres est une fonction. Les messages d'erreur et les motifs de contrôle
// sont rédigés par le moteur Rust : ils sont affichés tels quels et ne figurent
// pas ici.

export const textes = {
  application: {
    nom: "BPMN-Script",
    afficherDossier: "Afficher le dossier du traitement",
    fermer: "Fermer le traitement",
    themeSombre: "Thème sombre",
    etiquetteErreur: "Erreur",
  },

  // Libellés affichés pendant une action (« Lecture des correspondances… »).
  actions: {
    choixFichier: "Choix du fichier",
    choixDossier: "Choix du dossier",
    choixClasseur: "Choix du classeur",
    creation: "Copie et inventaire du SGX",
    ouverture: "Ouverture et vérification du traitement",
    fermeture: "Fermeture",
    ouvertureDossier: "Ouverture du dossier",
    ouvertureClasseur: "Ouverture du classeur",
    ouvertureAnalyse: "Ouverture de l'analyse",
    ouvertureRapport: "Ouverture du rapport",
    lectureCorrespondances: "Lecture des correspondances",
    preparationAnalyse: "Préparation de l'analyse",
    lectureDecisions: "Lecture et contrôle des décisions",
    generation: "Génération et vérification du SGX",
    copie: "Enregistrement de la copie",
  },

  etapes: {
    navigation: "Étapes du traitement",
    source: "Source",
    correspondances: "Correspondances",
    analyse: "Analyse",
    decisions: "Décisions",
    resultat: "Résultat",
    aRelire: "à relire",
    terminee: "terminée",
    enCours: "en cours",
  },

  // Statuts du moteur (Statut dans src/workflow.rs).
  statuts: {
    SgxProduit: "SGX produit",
    AucuneDecisionAdmissible: "Aucune décision admissible",
    ControleBloquant: "Contrôle bloquant",
    ProductionPossible: "Génération possible",
    DecisionsAttendues: "Décisions attendues",
    AnalyseSansImpact: "Aucun changement",
    InventaireTermine: "Inventaire",
  },

  accueil: {
    titre: "Harmoniser les noms de swimlanes d'un export Signavio",
    introduction:
      "Un traitement réunit un SGX, les classeurs Excel de correspondance et de décision, et les résultats. Il est enregistré dans un dossier que vous choisissez et peut être repris plus tard.",
    nouveauTitre: "Nouveau traitement",
    nouveauExplication:
      "Choisissez un export .sgx et le dossier qui accueillera le traitement. Le fichier choisi n'est jamais modifié : l'application travaille sur une copie.",
    changer: "Changer",
    choisirSgx: "Choisir le fichier SGX",
    choisirDossier: "Choisir le dossier des traitements",
    titreDialogueDossier: "Dossier qui accueillera le traitement",
    inventorier: "Inventorier les lanes",
    reprendreTitre: "Reprendre un traitement",
    reprendreExplication:
      "Ouvrez le dossier d'un traitement existant. Son état est vérifié : copie de la source, classeurs lus et résultats.",
    ouvrirTraitement: "Ouvrir un dossier de traitement",
    titreDialogueTraitement: "Ouvrir un dossier de traitement",
  },

  source: {
    titre: "Source",
    copie:
      "L'application travaille sur une copie contrôlée par empreinte, dans le dossier du traitement. L'original peut être déplacé sans gêner la reprise.",
    modeles: "modèles reconnus",
    occurrences: "occurrences de lanes",
    noms: "noms distincts",
    rienAHarmoniser: "Les modèles de ce SGX ne contiennent aucune lane nommée : il n'y a rien à harmoniser.",
    suivant: "Préparer les correspondances",
  },

  correspondances: {
    titre: "Correspondances",
    consigne: "Renseignez les nouveaux noms dans Excel. Une cellule Nouveau nom vide laisse le nom inchangé.",
    ouvrir: "Ouvrir le classeur",
    etiquetteARelire: "À relire",
    aRelire: "Ce classeur a changé depuis sa dernière lecture. Relisez-le pour actualiser le traitement.",
    etiquetteInfo: "Info",
    fermerAvantLecture: "Enregistrez puis fermez le classeur avant de le lire.",
    etiquetteLu: "Lu",
    lus: (nombre) => `${nombre} nom(s) avec une demande de renommage ont été lus.`,
    etiquetteAVerifier: "À vérifier",
    nomsInconnus: "Ces noms n'existent pas dans l'inventaire et n'auront aucun effet (faute de frappe ?) :",
    etiquetteInformation: "Information",
    nomsEnDoublon: "Ces noms sont renseignés plusieurs fois ; la dernière ligne est retenue :",
    lire: "Lire les correspondances",
    relire: "Relire les correspondances",
    importer: "Importer un classeur de correspondances",
    voirAnalyse: "Voir l'analyse",
    preparerAnalyse: "Préparer l'analyse",
  },

  analyse: {
    titre: "Analyse",
    etiquetteNonPreparee: "À faire",
    nonPreparee: "L'analyse n'est pas encore préparée : lisez les correspondances puis préparez l'analyse.",
    etiquetteResultat: "Résultat",
    aucunChangement: "Aucun changement proposé. Vérifiez les nouveaux noms renseignés.",
    retourCorrespondances: "Revenir aux correspondances",
    apercu: "Aperçu en lecture seule des changements proposés. Rien n'est encore modifié.",
    propositions: "propositions",
    occurrences: "occurrences visées",
    modeles: "modèles concernés",
    legende: "Une ligne par modèle et par nom ; des flux homonymes restent distincts par leur fichier modèle.",
    colonneFlux: "Flux",
    colonneNomActuel: "Nom actuel",
    colonneNouveauNom: "Nouveau nom",
    colonneOccurrences: "Occ.",
    colonneFichier: "Fichier modèle",
    etiquetteCopie: "Copie",
    copieEnregistree: (chemin) => `Copie enregistrée pour arbitrage : ${chemin}`,
    suivant: "Passer aux décisions",
    ouvrir: "Ouvrir l'analyse",
    copier: "Enregistrer une copie pour arbitrage",
  },

  decisions: {
    titre: "Décisions",
    consigne:
      "Renseignez OUI ou NON dans la colonne Validation, puis lisez le classeur enregistré. Les lignes absentes ne seront pas appliquées.",
    ouvrir: "Ouvrir le classeur de décision",
    etiquetteARelire: "À relire",
    aRelire:
      "Ce classeur a changé depuis sa dernière lecture. Relisez-le pour actualiser le traitement ; la génération est suspendue d'ici là.",
    correspondancesARelire:
      "Le classeur de correspondance a changé depuis sa dernière lecture. Relisez-le avant de générer le SGX.",
    etiquetteInfo: "Info",
    fermerAvantLecture:
      "Enregistrez puis fermez le classeur avant de le lire. Un retour d'arbitre s'importe tel quel : il est contrôlé ligne par ligne contre l'analyse.",
    lire: "Lire et contrôler les décisions",
    relire: "Relire et contrôler les décisions",
    importer: "Importer un retour d'arbitrage",
    dernierControle: "Dernier contrôle",
    dernierControleAActualiser: "Dernier contrôle — à actualiser",
    admises: "Admises",
    occurrencesPrevues: (nombre) => `${nombre} occurrences prévues`,
    refusees: "Refusées",
    refuseesDetail: "NON",
    ignorees: "Ignorées",
    ignoreesDetail: "OUI non conforme",
    enAttente: "En attente",
    enAttenteDetail: "sans OUI ni NON",
    sansDecision: "Sans décision",
    sansDecisionDetail: "propositions absentes du classeur",
    legende: "Lignes non admises : elles ne seront pas appliquées.",
    colonneLigne: "Ligne",
    colonneNomActuel: "Nom actuel",
    colonneNouveauNom: "Nouveau nom",
    colonneResultat: "Résultat",
    colonneMotif: "Motif",
    etiquetteBloquant: "Bloquant",
    bloquant:
      "Les modifications ne correspondent pas aux occurrences attendues. Aucun nouveau SGX ne peut être créé : corrigez les décisions ou les correspondances.",
    etiquetteAucunSgx: "Aucun SGX",
    aucuneAdmissible: "Aucune décision admissible : aucun SGX ne peut être généré.",
    etiquetteControle: "Contrôlé",
    controle: "Décisions contrôlées contre l'analyse ; le recomptage en mémoire est conforme.",
    generer: "Générer le SGX modifié",
    ouvrirRapport: "Ouvrir le rapport de contrôle",
  },

  resultat: {
    titre: "Résultat",
    etiquetteInterrompue: "Interrompue",
    interrompue:
      "Une production a été interrompue avant d'être enregistrée. Son contenu n'est pas confirmé et n'est jamais présenté comme un résultat :",
    etiquetteARelire: "À relire",
    entreesModifiees:
      "Un classeur a changé depuis sa dernière lecture : ce résultat correspond aux dernières entrées lues, pas au contenu actuel du classeur.",
    etiquetteProduit: "Produit",
    produit: "SGX produit et vérifié : relu après écriture, seules les lanes validées diffèrent de la source.",
    etiquetteAttention: "Attention",
    fichierAbsent: "Ce fichier a été supprimé depuis sa production.",
    fichierModifie: "Ce fichier a été modifié depuis sa production : il ne correspond plus au résultat vérifié.",
    enregistrerCopie: "Enregistrer une copie",
    etiquetteCopie: "Copie",
    copieEnregistree: (chemin) => `Copie enregistrée : ${chemin}`,
    modeles: "modèles concernés par la production",
    occurrences: "occurrences traitées",
    tentative: (numero) => `tentative ${numero}`,
    afficher: "Afficher le SGX dans le dossier",
    ouvrirRapport: "Ouvrir le rapport de contrôle",
    etiquetteSuivante: "Étape suivante",
    suivante:
      "Importez ce fichier dans un emplacement Signavio de test et vérifiez les modèles concernés avant tout import en production.",
    etiquetteAucunSgx: "Aucun SGX",
    aucunSgx: (cause) => `Aucun nouveau SGX n'a été créé : ${cause}`,
    causeAucuneAdmissible: "aucune décision admissible (lignes refusées, en attente ou non conformes).",
    causeBloquant: "le recomptage des occurrences ne correspond pas aux décisions.",
    retourDecisions: "Revenir aux décisions",
    aucunResultat: "Aucun résultat pour les correspondances et décisions actuellement lues.",
    precedents: "Résultats précédents",
    precedentsExplication: "Non produits à partir des correspondances et décisions actuellement lues.",
    tentativeDatee: (numero, date) => `Tentative ${numero} · ${date}`,
  },

  bilan: {
    region: "Bilan du traitement",
    titre: "Traitement",
    modeles: "Modèles",
    occurrences: "Occurrences",
    noms: "Noms distincts",
    demandesLues: "Demandes lues",
    propositions: "Propositions",
    admises: "Décisions admises",
    aActualiser: "à actualiser",
    source: (nom) => `Source : ${nom}, copie contrôlée par empreinte.`,
    derniereTentative: "Dernière tentative",
    tentative: (numero) => `Tentative ${numero}`,
    entreesActuelles: "entrées actuelles",
    entreesPrecedentes: "entrées précédentes",
    interrompues: (nombre) => `${nombre} tentative(s) interrompue(s)`,
  },
};
